%% define data locations:
participants10 = {...
    'AR_handles.mat',...
    'DL_handles.mat',...
    'HM_handles.mat',...
    'JI_handles.mat',...
    'RH_handles.mat',...
    'FO_SW_handles.mat',...
    'CK_NW_handles.mat',...
    'AC_W_handles.mat',...
    'JD_NW_handles.mat',...
    'CC_W_handles.mat',...
}; %complete with 10

participants5 = {...
    'TM_handles.mat',...
    'BM_E_handles.mat',...
    'VJ_NE_handles.mat',...
    'BK_N_handles.mat'...
    'MS_NE_handles.mat',...
    'SS_W_handles.mat',...
    'DB_NW_handles.mat',...
    'AT_NE_handles.mat',...
    ...'DX_handles_nm5_W.mat',... %% This subject must be excluded (did not return on day 2- returned 3 days later )
    'YZ_SW_handles.mat',...
    'LD_N_handles.mat',...
}; %complete with 10

participants30 = {...   
    'YR_N_handles_b.mat',...
    'HP_N_handles.mat',...
    'BM_handles_NE.mat',...
    ...'AlexisR_SW_handles.mat',... %lefty
    'HM_N_handles_0724.mat',...
    'RT_NW_handles.mat',...
    'MF_W_handles.mat',...
    'DE_NE_handles.mat',...
    'KR_NW_handles.mat',...
    'BE_NE_handles.mat',...
    'UE_NE_handles.mat',...
}; % complete with 10

participants2 = {...
    'AS_NE_handles.mat',...
    'AH_SW_handles.mat',...
    'EL_NE_handles.mat',...
    'MC_N_handles.mat',...
    'SX_N_handles.mat',...
    'PG_E_handles.mat',...
    'BA_SW_handles.mat',...
    'CO_E_handles.mat',...
    'DT_N_handles_fix.mat',...
    'JS_NW_handles.mat',...
}; % complete with 10.


participants15Deg = {...
    ...'DMH_handles_15Deg_fixed.mat',... cannot include myself as subject
    'RA_E_handles.mat',...
    'NK_SW_handles_fixed.mat',...
    'EV_W_handles_fixed.mat',...
    'RN_SW_handles_fixed.mat',...
    'NL_NE_handles.mat',...
    'JH_NW_handles.mat',...
    'CT_NE_handles.mat',...
    'YL_W_handles.mat',...
    'YH_NE_handles.mat',...
    'RD_N_handles.mat',...
}; % complete with 10



participantsC = {...
    ...'KB_NE_handles.mat',...
    ...'KB_NW_handles.mat',...
    ...'KB_N_handles.mat',...
    ...'MS_handles_NM0_N.mat',...
    ...'MS_handles_NM0_E.mat',...
    ...'DH_SW_handles.mat',...
    'DH_SW_handles_mod.mat',...
    'AHb_NE_handles.mat',...
    'KM_N_handles_c.mat',...
    'ER_SW_handles.mat',...
    'GP_NE_handles.mat',...
    'WA_W_handles.mat',...
    'SHP_NE_handles.mat',...
    'MB_SW_handles.mat',...
    'BS_N_handles.mat',...
    'BL_N_handles.mat',...
    }; %complete with 10 

participants5_1day = {...'AD_N_handles.mat',...
    'SS_NW_handles.mat',...
    'BR_NE_handles.mat',...
    'AK_W_handles.mat',...
    'NC_N_handles.mat',...
    'GS_NW_handles.mat',...
    'AU_N_handles.mat',...
    'KK_W_handles.mat',...
    'AD_W_handles.mat',...
    'KS_NE_handles.mat',...
    'TF_NE_handles.mat',...
    }; % complete with 10

participants5_counter = {...
    'CS_NW_handles.mat',...
    'MAD_W_handles.mat',...
    'WN_NW_handles.mat',...
    'ML_N_handles.mat',...
    'TK_W_handles.mat',...
    'RC_E_handles.mat',...
    'RR_N_handles.mat',...
    }; 

participants5_counter_24 = {
    'WA_NW_handles.mat',...
    'NG_NE_handles.mat',...
    'YW_W_handles.mat',...
    'MJ_N_handles.mat',...
    'JS_NE_handles_b.mat',...
    'JO_N_handles.mat',...
    'SAD_W_handles.mat',...
    'LM_N_handles.mat',...
    'TT_N_handles.mat',...
    'OA_NW_handles.mat',...
    }; %complete with 10

%% collect data into structure organied by group:

dat_struc = struct('group', struct('subject', struct('trial', struct('x', [], 'y', [], 'dir', [], 'vMag', [], 'aMag', [], 'scalarDir', [], 'rotation', []))));

Ts = 1/130;
k_200ms = round(.2/Ts);
% k_200ms = round(.3/Ts);

for isub = 1:length(participantsC)
    load(participantsC{isub})
    for itr = 1:size(handles.X_filt,1)
        dat_struc.group(1).subject(isub).trial(itr).x = handles.X_filt(itr,~isnan(handles.X_filt(itr,:)));
        dat_struc.group(1).subject(isub).trial(itr).y = handles.Y_filt(itr,~isnan(handles.Y_filt(itr,:)));
        dat_struc.group(1).subject(isub).trial(itr).dir = handles.dir_signal(itr,~isnan(handles.dir_signal(itr,:)));
        dat_struc.group(1).subject(isub).trial(itr).vMag = handles.vMag(itr,~isnan(handles.vMag(itr,:)));
        dat_struc.group(1).subject(isub).trial(itr).aMag = handles.dvdt(itr,~isnan(handles.dvdt(itr,:)));
        try
            if ~isnan(handles.mvt_init(itr))
                dat_struc.group(1).subject(isub).trial(itr).scalarDir = handles.dir_signal(itr, handles.mvt_init(itr) + k_200ms);
            else
                dat_struc.group(1).subject(isub).trial(itr).scalarDir = nan;
            end
        catch
            dat_struc.group(1).subject(isub).trial(itr).scalarDir = nan;
        end
        dat_struc.group(1).subject(isub).trial(itr).rotation = handles.rotation(itr);
    end
end

for isub = 1:length(participants2)
    load(participants2{isub})
    for itr = 1:size(handles.X_filt,1)
        dat_struc.group(2).subject(isub).trial(itr).x = handles.X_filt(itr,~isnan(handles.X_filt(itr,:)));
        dat_struc.group(2).subject(isub).trial(itr).y = handles.Y_filt(itr,~isnan(handles.Y_filt(itr,:)));
        dat_struc.group(2).subject(isub).trial(itr).dir = handles.dir_signal(itr,~isnan(handles.dir_signal(itr,:)));
        dat_struc.group(2).subject(isub).trial(itr).vMag = handles.vMag(itr,~isnan(handles.vMag(itr,:)));
        dat_struc.group(2).subject(isub).trial(itr).aMag = handles.dvdt(itr,~isnan(handles.dvdt(itr,:)));
        try
            if ~isnan(handles.mvt_init(itr))
                dat_struc.group(2).subject(isub).trial(itr).scalarDir = handles.dir_signal(itr, handles.mvt_init(itr) + k_200ms);
            else
                dat_struc.group(2).subject(isub).trial(itr).scalarDir = nan;
            end
        catch
            dat_struc.group(2).subject(isub).trial(itr).scalarDir = nan; 
        end
        dat_struc.group(2).subject(isub).trial(itr).rotation = handles.rotation(itr);
    end
end

for isub = 1:length(participants5)
    load(participants5{isub})
    for itr = 1:size(handles.X_filt,1)
        dat_struc.group(3).subject(isub).trial(itr).x = handles.X_filt(itr,~isnan(handles.X_filt(itr,:)));
        dat_struc.group(3).subject(isub).trial(itr).y = handles.Y_filt(itr,~isnan(handles.Y_filt(itr,:)));
        dat_struc.group(3).subject(isub).trial(itr).dir = handles.dir_signal(itr,~isnan(handles.dir_signal(itr,:)));
        dat_struc.group(3).subject(isub).trial(itr).vMag = handles.vMag(itr,~isnan(handles.vMag(itr,:)));
        dat_struc.group(3).subject(isub).trial(itr).aMag = handles.dvdt(itr,~isnan(handles.dvdt(itr,:)));
        try
            if ~isnan(handles.mvt_init(itr))
                dat_struc.group(3).subject(isub).trial(itr).scalarDir = handles.dir_signal(itr, handles.mvt_init(itr) + k_200ms);
            else
                dat_struc.group(3).subject(isub).trial(itr).scalarDir = nan;
            end
        catch
            dat_struc.group(3).subject(isub).trial(itr).scalarDir = nan;
        end
        dat_struc.group(3).subject(isub).trial(itr).rotation = handles.rotation(itr);
    end
end

for isub = 1:length(participants10)
    load(participants10{isub})
    for itr = 1:size(handles.X_filt,1)
        dat_struc.group(4).subject(isub).trial(itr).x = handles.X_filt(itr,~isnan(handles.X_filt(itr,:)));
        dat_struc.group(4).subject(isub).trial(itr).y = handles.Y_filt(itr,~isnan(handles.Y_filt(itr,:)));
        dat_struc.group(4).subject(isub).trial(itr).dir = handles.dir_signal(itr,~isnan(handles.dir_signal(itr,:)));
        dat_struc.group(4).subject(isub).trial(itr).vMag = handles.vMag(itr,~isnan(handles.vMag(itr,:)));
        dat_struc.group(4).subject(isub).trial(itr).aMag = handles.dvdt(itr,~isnan(handles.dvdt(itr,:)));
        try
            if ~isnan(handles.mvt_init(itr))
                dat_struc.group(4).subject(isub).trial(itr).scalarDir = handles.dir_signal(itr, handles.mvt_init(itr) + k_200ms);
            else
                dat_struc.group(4).subject(isub).trial(itr).scalarDir = nan;
            end
        catch
            dat_struc.group(4).subject(isub).trial(itr).scalarDir = nan;
        end
        dat_struc.group(4).subject(isub).trial(itr).rotation = handles.rotation(itr);
    end
end

for isub = 1:length(participants30)
    load(participants30{isub})
    for itr = 1:size(handles.X_filt,1)
        dat_struc.group(5).subject(isub).trial(itr).x = handles.X_filt(itr,~isnan(handles.X_filt(itr,:)));
        dat_struc.group(5).subject(isub).trial(itr).y = handles.Y_filt(itr,~isnan(handles.Y_filt(itr,:)));
        dat_struc.group(5).subject(isub).trial(itr).dir = handles.dir_signal(itr,~isnan(handles.dir_signal(itr,:)));
        dat_struc.group(5).subject(isub).trial(itr).vMag = handles.vMag(itr,~isnan(handles.vMag(itr,:)));
        dat_struc.group(5).subject(isub).trial(itr).aMag = handles.dvdt(itr,~isnan(handles.dvdt(itr,:)));
        try
            if ~isnan(handles.mvt_init(itr))
                dat_struc.group(5).subject(isub).trial(itr).scalarDir = handles.dir_signal(itr, handles.mvt_init(itr) + k_200ms);
            else
                dat_struc.group(5).subject(isub).trial(itr).scalarDir = nan;
            end
        catch
            dat_struc.group(5).subject(isub).trial(itr).scalarDir = nan;
        end
        dat_struc.group(5).subject(isub).trial(itr).rotation = handles.rotation(itr);
    end
end

for isub = 1:length(participants15Deg)
    load(participants15Deg{isub})
    for itr = 1:size(handles.X_filt,1)
        dat_struc.group(6).subject(isub).trial(itr).x = handles.X_filt(itr,~isnan(handles.X_filt(itr,:)));
        dat_struc.group(6).subject(isub).trial(itr).y = handles.Y_filt(itr,~isnan(handles.Y_filt(itr,:)));
        dat_struc.group(6).subject(isub).trial(itr).dir = handles.dir_signal(itr,~isnan(handles.dir_signal(itr,:)));
        dat_struc.group(6).subject(isub).trial(itr).vMag = handles.vMag(itr,~isnan(handles.vMag(itr,:)));
        dat_struc.group(6).subject(isub).trial(itr).aMag = handles.dvdt(itr,~isnan(handles.dvdt(itr,:)));
        try
            if ~isnan(handles.mvt_init(itr))
                dat_struc.group(6).subject(isub).trial(itr).scalarDir = handles.dir_signal(itr, handles.mvt_init(itr) + k_200ms);
            else
                dat_struc.group(6).subject(isub).trial(itr).scalarDir = nan;
            end
        catch
            dat_struc.group(6).subject(isub).trial(itr).scalarDir = nan;
        end
        dat_struc.group(6).subject(isub).trial(itr).rotation = handles.rotation(itr);
    end
end

for isub = 1:length(participants5_1day)
    load(participants5_1day{isub})
    for itr = 1:size(handles.X_filt,1)
        dat_struc.group(7).subject(isub).trial(itr).x = handles.X_filt(itr,~isnan(handles.X_filt(itr,:)));
        dat_struc.group(7).subject(isub).trial(itr).y = handles.Y_filt(itr,~isnan(handles.Y_filt(itr,:)));
        dat_struc.group(7).subject(isub).trial(itr).dir = handles.dir_signal(itr,~isnan(handles.dir_signal(itr,:)));
        dat_struc.group(7).subject(isub).trial(itr).vMag = handles.vMag(itr,~isnan(handles.vMag(itr,:)));
        dat_struc.group(7).subject(isub).trial(itr).aMag = handles.dvdt(itr,~isnan(handles.dvdt(itr,:)));
        
        try
            if ~isnan(handles.mvt_init(itr))
                dat_struc.group(7).subject(isub).trial(itr).scalarDir = handles.dir_signal(itr, handles.mvt_init(itr) + k_200ms);
            else
                dat_struc.group(7).subject(isub).trial(itr).scalarDir = nan;
            end
        catch
            dat_struc.group(7).subject(isub).trial(itr).scalarDir = nan;
        end
        dat_struc.group(7).subject(isub).trial(itr).rotation = handles.rotation(itr);
    end
end

for isub = 1:length(participants5_counter_24)
    load(participants5_counter_24{isub})
    for itr = 1:size(handles.X_filt,1)
        dat_struc.group(8).subject(isub).trial(itr).x = handles.X_filt(itr,~isnan(handles.X_filt(itr,:)));
        dat_struc.group(8).subject(isub).trial(itr).y = handles.Y_filt(itr,~isnan(handles.Y_filt(itr,:)));
        dat_struc.group(8).subject(isub).trial(itr).dir = handles.dir_signal(itr,~isnan(handles.dir_signal(itr,:)));
        dat_struc.group(8).subject(isub).trial(itr).vMag = handles.vMag(itr,~isnan(handles.vMag(itr,:)));
        dat_struc.group(8).subject(isub).trial(itr).aMag = handles.dvdt(itr,~isnan(handles.dvdt(itr,:)));
        try
            if ~isnan(handles.mvt_init(itr))
                dat_struc.group(8).subject(isub).trial(itr).scalarDir = handles.dir_signal(itr, handles.mvt_init(itr) + k_200ms);
            else
                dat_struc.group(8).subject(isub).trial(itr).scalarDir = nan;
            end
        catch
            dat_struc.group(8).subject(isub).trial(itr).scalarDir = nan;
        end
        dat_struc.group(8).subject(isub).trial(itr).rotation = handles.rotation(itr);
    end
end